### PR TITLE
fix: add prefer-in-document to recommended config

### PR DESCRIPTION
**Pull request by nickmccurdy**
**What**: add prefer-in-document to recommended config

**Why**: this is a useful rule that's in line with other best practices that the recommended config follows

**How**: enabled recommended flag

**Checklist**:

- [x] Documentation
- [ ] Tests N/A
- [x] Ready to be merged

### CODE REVIEW

**Review by AntonNiklasson — COMMENTED** [review]
I agree it should be recommended. I'll leave to Ben to decide though.

**Comment by AriPerkkio** [comment]
FYI @nickmccurdy before adding this rule as recommended check the latest added smoke tests, [PR](https://github.com/testing-library/eslint-plugin-jest-dom/pull/113). `prefer-in-document` is crashing on many repositories. Here's one example:

## Rule: prefer-in-document
- Message: `Cannot read property 'name' of undefined
Occurred while linting <text>:159`
- Path: `gatsbyjs/gatsby/integration-tests/structured-logging/__tests__/logs.js`
- [Link](https://github.com/gatsbyjs/gatsby/blob/HEAD/integration-tests/structured-logging/__tests__/logs.js#L159)
```js
        event.type === `LOG_ACTION` &&
        event.action.type === `ACTIVITY_END` &&
        event.action.payload.id === `createPages`
    )
    expect(createPagesEndActivityEvent).toBeDefined()
    expect(createPagesEndActivityEvent.action.payload.status).toBe(`FAILED`)
  })
  ;[`success`, `info`, `warn`, `log`, `error`].forEach(level => {
    // success, info and log all emit `INFO`
    const mapActionToLevel = {
```
```
TypeError: Cannot read property 'name' of undefined
Occurred while linting <text>:159
    at check (/<root-path-removed>/eslint-plugin-jest-dom/dist/rules/prefer-in-document.js:39:27)
    at CallExpression[callee.object.callee.name='expect'][callee.property.name=/(toHaveLength|toBeDefined|toBeNull)/] (/<root-path-removed>/eslint-plugin-jest-dom/dist/rules/prefer-in-document.js:97:7)
    at /<root-path-removed>/eslint-plugin-jest-dom/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/<root-path-removed>/eslint-plugin-jest-dom/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/<root-path-removed>/eslint-plugin-jest-dom/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/<root-path-removed>/eslint-plugin-jest-dom/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/<root-path-removed>/eslint-plugin-jest-dom/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/<root-path-removed>/eslint-plugin-jest-dom/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /<root-path-removed>/eslint-plugin-jest-dom/node_modules/eslint/lib/linter/linter.js:952:32
```

**Comment by benmonro** [comment]
let's hold off on merging this until #107 is implemented and we've had a chance to smoke test it more to make sure there's nothing crazy out there.

**Review by benmonro — APPROVED** [review]

**Comment by benmonro** [comment]
all the smoke test issues have been resolved. changing to recommended. 👍

**Pull request merged**
