### PR TITLE
feat: new rule prefer-to-have-attribute

### PR DESCRIPTION
**Pull request by benmonro**

### CODE REVIEW

**Comment by benmonro** [comment]
@nickmccurdy @gnapse i just published a new version w/ this new rule for `prefer-to-have-attribute` (see readme for details).  was hoping either or both of you might be able to give this new rule a spin and give me any feedback you might have.  many thx in advance

**Comment by nickmccurdy** [comment]
This seems useful, shouldn't it be recommended?

**Comment by benmonro** [comment]
Yeah but wanted someone else to try it out first before that.

**Comment by nickmccurdy** [comment]
Seems to be working 😄I vote we recommend it

```js
// error  Use toHaveAttribute instead of asserting on getAttribute  jest-dom/prefer-to-have-attribute
expect(button.getAttribute("type")).toBe("button");
```

**Pull request merged**
