### PR TITLE
fix: pin kcd-scripts at 6.5

### PR DESCRIPTION
**Pull request by benmonro**
**What**:

**Why**:

**How**:

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

### CODE REVIEW

**Comment by benmonro** [comment]
@MichaelDeBoey could use your help if you have any time.  for some reason the latest version of kcd-scripts is causing errors on ajv.  only thing i've found to fix this is to pin kcd-scripts@5.

**Comment by MichaelDeBoey** [comment]
@benmonro Do you have a more detailed thing that I can have a look at?

**Comment by benmonro** [comment]
Yeah just bump kcd scripts to latest and run yarn test

**Comment by MichaelDeBoey** [comment]
@kentcdodds I tried to fix this (see #89 & #91), but can't figure out the cause.
Problem is also appearing with latest `kcd-scripts` (see #93 & #94)

**Comment by kentcdodds** [comment]
Based on those I have no idea what this could be. Doesn't look related to kcd-scripts 🤷‍♂️

**Comment by MichaelDeBoey** [comment]
Seems like it has something to do with dependencies of `kcd-scripts` as `6.5` is working, but higher isn't anymore 🤔😕

**Comment by MichaelDeBoey** [comment]
Is https://github.com/rollup/plugins/issues/640 going to fix this one too? 🤔

**Comment by kentcdodds** [comment]
Potentially. I haven't looked into the issues here. But if it is that issue, you can work around it by adding `@types/estree` to your `devDependencies`.

**Comment by MichaelDeBoey** [comment]
Nope, seems like adding `@types/estree` isn't fixing the `TypeError: Ajv is not a constructor` error 😢

**Pull request merged**
