### PR TITLE
Add recommended config

### PR DESCRIPTION
**Pull request by nickmccurdy**
This allows using `"extends": ["plugin:jest-dom/recommended"]` to enable the plugin and all recommended rules.

### CODE REVIEW

**Comment by benmonro** [comment]
Thanks @nickmccurdy  as soon as I get all contributors setup I'll add you

**Comment by nickmccurdy** [comment]
I'm working on generating the config automatically from the rules, would you still find this useful?

**Comment by benmonro** [comment]
Sure!

**Pull request merged**
