### PR TITLE
fix: remove unneeded dependency on `@babel/runtime`

### PR DESCRIPTION
**Pull request by G-Rath**
**What**:

Removes `@babel/runtime` as a dependency

**Why**:

I can't find any place where we actually use it, and everything seems to be fine without it...

**How**:

`npm un @babel/runtime`

**Checklist**:

- [ ] Documentation N/A
- [ ] Tests N/A
- [x] Ready to be merged

### CODE REVIEW

**Comment by G-Rath** [comment]
Ah I see what's going on - it's used in the dist files as an optimisation, which doesn't get used when running tests 👍

**Comment by MichaelDeBoey** [comment]
`kcd-scripts` will also throw an error for this when it's not included in the dependencies

**Comment by G-Rath** [comment]
Yeah, but only when you run `build` 😅

**Comment by MichaelDeBoey** [comment]
Indeed.

Since that's run in the `validate` script, that's not a problem imo

**Pull request closed without merging**
